### ISSUE TITLE
Indentation 

### ISSUE THREAD

**Issue by kevinsimper** [unexpectedjs/unexpected-http#3]
It makes it hard to read the code with that much indentation.

Also the `options` you can pass to the request, could be highlighted by a comment or two.

**Comment by papandreou** [comment]
PR welcome :)

**Comment by sunesimonsen** [comment]
@kevinsimper do you mean the nesting level or the 4 spaces indentation?

**Comment by papandreou** [comment]
The library is only halfway promisified. Once that's fixed I hope it'll be less unbearable to look at.

**Comment by papandreou** [comment]
Switched to 2 space indentation and prettier now, hopefully that helped :smirk:

**Comment by kevinsimper** [comment]
@papandreou It is awesome, I appreciate the friendly comments 😍
